export const WARDS = [
  "Phường Hải Vân",
  "Phường Liên Chiểu",
  "Phường Hòa Khánh",
  "Phường Thanh Khê",
  "Phường Hải Châu",
  "Phường Hòa Cường",
  "Phường Cẩm Lệ",
  "Phường Sơn Trà",
  "Phường An Hải",
  "Phường Ngũ Hành Sơn",
  "Phường An Khê",
  "Phường Hòa Xuân",
  "Phường Bàn Thạch",
  "Phường Tam Kỳ",
  "Phường Hương Trà",
  "Phường Quảng Phú",
  "Phường Hội An Tây",
  "Phường Hội An",
  "Phường Hội An Đông",
  "Phường Điện Bàn",
  "Phường Điện Bàn Bắc",
  "Phường An Thắng",
  "Phường Điện Bàn Đông",
];
